name: webstore
recipe: symfony
excludes:
  - htdocs/vendor
  - htdocs/var/cache
  - htdocs/node_modules
config:
  database: mysql:5.7
  php: '8.2'
  config:
  webroot: htdocs/public
  composer_version: 2-latest
services:
  node:
    type: 'node:18'
tooling:
  npm:
    service: node
    dir: /app/htdocs
  composer:
    service: appserver
    cmd: composer
    dir: /app/htdocs
  console:
    service: appserver
    cmd: htdocs/bin/console
  c:
    service: appserver
    cmd: htdocs/bin/console
  symfony:
    service: appserver
    dir: /app/htdocs